export { runMigrations, getCurrentVersion } from "./db/run-migrations.js";

export * from "./shared/index.js";
export * from "./domain/shared/index.js";
export * from "./domain/project/index.js";
export * from "./domain/ports/index.js";
export {
	Milestone,
	type MilestoneState,
	MilestoneCreatedEvent,
	MilestoneTransitionedEvent,
	MilestoneArchivedEvent,
	MilestoneNotFoundError,
	MilestoneAlreadyArchivedError,
	type MilestoneProps,
	type MilestoneUpdateProps,
	type MilestoneStatus,
	MILESTONE_STATUSES,
	MILESTONE_TRANSITIONS,
	InvalidTransitionError as MilestoneInvalidTransitionError,
} from "./domain/milestone/index.js";
export {
	Slice,
	type SliceState,
	Review,
	type ReviewState,
	Phase,
	PHASE_VALUES,
	PIPELINE_PHASE_ORDER,
	BranchName,
	SliceDependency,
	type SliceKind,
	SliceCreatedEvent,
	SliceTransitionedEvent,
	SliceTierClassifiedEvent,
	SliceArchivedEvent,
	ReviewRecordedEvent,
	ReviewVerdictSetEvent,
	TierClassificationError,
	SliceNotFoundError,
	SliceAlreadyArchivedError,
	PreconditionViolationError,
	type SliceProps,
	type SliceUpdateProps,
	InvalidTransitionError as SliceInvalidTransitionError,
	type SliceStatus,
	type ComplexityTier,
	SLICE_STATUSES,
	SLICE_TRANSITIONS,
	HUMAN_GATES,
	TIERS,
	type GuardResult,
	tierSkipGuard,
	reviewExistsGuard,
	type PhaseRun,
	type ArtifactStatus,
	nextSliceStatus,
	computeSliceStatus,
	type TransitionViolation,
	type TransitionResult,
	validateTransition,
} from "./domain/slice/index.js";
export {
	Task,
	type TaskState,
	TaskCreatedEvent,
	TaskClaimedEvent,
	TaskClosedEvent,
	TaskUnclaimedEvent,
	AlreadyClaimedError,
	TaskNotFoundError,
	type TaskProps,
	type TaskUpdateProps,
	type Difficulty,
	type TaskStatus,
	TASK_STATUSES,
	TASK_TRANSITIONS,
} from "./domain/task/index.js";
export {
	RoutingOutcome,
	type RoutingOutcomeProps,
	type OutcomeDimension,
	type OutcomeVerdict,
	type OutcomeSourceKind,
	JudgeVerdict,
	type JudgeVerdictProps,
	type JudgeDimension,
	type JudgeVerdictValue,
} from "./domain/routing/index.js";
export { Observation, type ObservationProps } from "./domain/observation/index.js";
export {
	TFF_DIR,
	tffPath,
	milestoneDir,
	sliceDir,
	worktreeDir,
	OBSERVATIONS_DIR,
	SETTINGS_FILE,
	PROJECT_FILE,
	STATE_FILE,
	MILESTONES_DIR,
	STATE_DB_FILE,
	QUICK_DIR,
	DEBUG_DIR,
	quickSliceDir,
	debugSliceDir,
	sliceDirFor,
} from "./shared/paths.js";

export * from "./contract/index.js";
