export { runMigrations, getCurrentVersion } from "./db/run-migrations.js";

export * from "./domain/shared/index.js";
export * from "./domain/project/index.js";
export {
	Milestone,
	type MilestoneState,
	MilestoneCreatedEvent,
	MilestoneTransitionedEvent,
	MilestoneArchivedEvent,
	MilestoneNotFoundError,
	MilestoneAlreadyArchivedError,
	MilestoneRepository,
	type MilestoneStatus,
	MILESTONE_TRANSITIONS,
	InvalidTransitionError as MilestoneInvalidTransitionError,
} from "./domain/milestone/index.js";
export {
	Slice,
	type SliceState,
	Review,
	type ReviewState,
	Phase,
	PHASE_VALUES,
	PIPELINE_PHASE_ORDER,
	BranchName,
	SliceDependency,
	type SliceKind,
	SliceCreatedEvent,
	SliceTransitionedEvent,
	SliceTierClassifiedEvent,
	SliceArchivedEvent,
	ReviewRecordedEvent,
	ReviewVerdictSetEvent,
	TierClassificationError,
	SliceNotFoundError,
	SliceAlreadyArchivedError,
	PreconditionViolationError,
	SliceRepository,
	InvalidTransitionError as SliceInvalidTransitionError,
	type SliceStatus,
	type ComplexityTier,
	SLICE_TRANSITIONS,
	HUMAN_GATES,
	type GuardResult,
	tierSkipGuard,
	reviewExistsGuard,
	type PhaseRun,
	type ArtifactStatus,
	nextSliceStatus,
	computeSliceStatus,
	type TransitionViolation,
	type TransitionResult,
	validateTransition,
} from "./domain/slice/index.js";
export {
	Task,
	type TaskState,
	TaskCreatedEvent,
	TaskClaimedEvent,
	TaskClosedEvent,
	TaskUnclaimedEvent,
	AlreadyClaimedError,
	TaskNotFoundError,
	TaskRepository,
	type TaskStatus,
	TASK_TRANSITIONS,
} from "./domain/task/index.js";
